#ifndef CONFIG_SETTINGS_H
#define CONFIG_SETTINGS_H

//
//
// Keyboard Settings
//

#define KB_KEY_THRESHOLD_DEFAULT 50
#define KB_KEY_MAX_VALUE_THRESHOLD_DEFAULT 1023
#define KB_DEFAULT_POLLING_RATE 1
#define KB_ADC_SAMPLING_DEFAULT ADC_SMP_2_5_CYCLES
#define KB_KEY_COUNT 35

#define MUX_ENABLED 1
#define MUX1_KEY_COUNT 11
#define MUX2_KEY_COUNT 15
#define MUX3_KEY_COUNT 9

#define BOOT0_HANDLER_ENABLED 1

#define USB_ENABLED 1

#define DEBUG_UART_ENABLED 1
#define DEBUG_SWO_ENABLED 1
#define LOG_LEVEL LOG_LEVEL_DEBUG
#define DEBUG_UART_INSTANCE LPUART1
#define DBG_LONG_BLINK_DELAY 1000
#define DBG_SHORT_BLINK_DELAY 300

#endif // SETTINGS_H
