#ifndef HAL_ERR_H
#define HAL_ERR_H

typedef int hal_err;

#define OK 0

#define ERR_NOT_IMPLEMENTED -101

#define ERR_NVIC_SET_PRIO_SP_INV -201
#define ERR_NVIC_SET_PRIO_PP_INV -202

#define ERR_GPIO_SET_INTF_WR_PN -401
#define ERR_GPIO_SET_INTR_WR_PN -402
#define ERR_GPIO_SET_INT_WR_PN -403
#define ERR_GPIO_SET_INT_WR_GPIO -404

#define ERR_SYSTICK_INIT_FREQ_INV -501
#define ERR_SYSTICK_INIT_FREQ_CONFIG -502

#define ERR_CRS_SET_SM_T_INV_TRIM -601

#define ERR_USB_INIT_HANDLE_NULL -701
#define ERR_USB_INIT_INSTANCE_NULL -702

#define ERR_ADC_INIT_ARGNULL -800
#define ERR_ADC_INIT_BUSY -801
#define ERR_ADC_INIT_INV_SEQ_CONV -802
#define ERR_ADC_INIT_ADVREGEN_FAULT -803
#define ERR_ADC_INIT_CONV_ONGOING -804
#define ERR_ADC_CHCONF_BUSY -805
#define ERR_ADC_CHCONF_INV_OFFSET -806
#define ERR_ADC_CHCONF_INV_OFFSETTYPE -807
#define ERR_ADC_CHCONF_INV_MODE4CH -808
#define ERR_ADC_CHCONF_CONV_ONGOING -809
#define ERR_ADC_DISABLE_CONV_ONGOING -810
#define ERR_ADC_DISABLE_TIMEOUT -811
#define ERR_ADC_ENABLE_REQUIREMENTS -812
#define ERR_ADC_ENABLE_TIMEOUT -813
#define ERR_ADC_CALIB_BUSY -814
#define ERR_ADC_CALIB_TIMEOUT -815
#define ERR_ADC_STARTIT_CONV_ONGOING -816
#define ERR_ADC_STARTIT_BUSY -817
#define ERR_ADC_STOPIT_BUSY -818
#define ERR_ADC_STOPCONV_TIMEOUT -819
#define ERR_ADC_STARTDMA_BUSY -820
#define ERR_ADC_STARTDMA_BADARGS -821
#define ERR_ADC_START_BUSY -822

#define ERR_UART_INIT_ARGNULL -900
#define ERR_UART_INIT_INV_PINCONFIG -901
#define ERR_UART_INIT_UNKNOWN_INSTANCE -902
#define ERR_UART_CONFIG_INV_CS -903
#define ERR_UART_CONFIG_INV_PCLK -904
#define ERR_UART_CONFIG_INV_BR -905
#define ERR_UART_CONFIG_INV_DIV -906
#define ERR_UART_WOF_TIMEOUT -907
#define ERR_UART_WOF_BLOCK -908
#define ERR_UART_SETTXFIFO_BUSY -910
#define ERR_UART_SETRXFIFO_BUSY -911
#define ERR_UART_FIFOEN_BUSY -912
#define ERR_UART_FIFODIS_BUSY -913
#define ERR_UART_TX_BUSY -914
#define ERR_UART_TX_BADARGS -915
#define ERR_UART_RX_BUSY -916
#define ERR_UART_RX_BADARGS -917

#define ERR_I2C_INIT_ARGNULL -1000
#define ERR_I2C_INIT_INSTANCENULL -1001

#define ERR_DMA_STARTIT_BADARGS -1100
#define ERR_DMA_STARTIT_BUSY -1101
#define ERR_DMA_INIT_BADARGS -1102

#define ERR_FLASH_UNLOCK -1200
#define ERR_FLASH_LOCK -1201
#define ERR_FLASH_ERASE_BUSY -1202
#define ERR_FLASH_WFOP_BSY_TIMEOUT -1203
#define ERR_FLASH_WFOP_ERRFLAG -1204
#define ERR_FLASH_WFOP_CFGBSY_TIMEOUT -1205
#define ERR_FLASH_PAGE_ERASE_NOTAPAGE -1206
#define ERR_FLASH_PROGRAM_ADDRNOTALIGNED -1207
#define ERR_FLASH_PROGRAM_NOTPROGRAMADDR -1208
#define ERR_FLASH_PROGRAM_ADDRNOTFASTPROG -1209
#define ERR_FLASH_PROGRAM_BUSY -1210

#define ERR_PERIPHCLK_CONFIGPLLSAI1_OFF_TIMEOUT -1300
#define ERR_PERIPHCLK_CONFIGPLLSAI1_ON_TIMEOUT -1301
#define ERR_PERIPHCLK_RTCSEL_LSE_TIMEOUT -1302

#define ERR_IPCC_INIT_BADARGS -1400

#define ERR_HSEM_LOCK_FAIL -1500
#define ERR_HSEM_LOCK_FAST_FAIL -1501

#endif // HAL_ERR_H
