#ifndef HAL_GPIO_H
#define HAL_GPIO_H

#include "hal_adc.h"

#include <stdbool.h>

// ===== Core types =====

typedef GPIO_TypeDef gpio_t;

typedef enum {
    GPIO_MODE_INPUT = 0b00,
    GPIO_MODE_OUTPUT = 0b01,
    GPIO_MODE_AF = 0b10,
    GPIO_MODE_ANALOG = 0b11,
} gpio_mode;

typedef enum {
    GPIO_AF_MODE_0 = 0,
    GPIO_AF_MODE_1 = 1,
    GPIO_AF_MODE_2 = 2,
    GPIO_AF_MODE_3 = 3,
    GPIO_AF_MODE_4 = 4,
    GPIO_AF_MODE_5 = 5,
    GPIO_AF_MODE_6 = 6,
    GPIO_AF_MODE_7 = 7,
    GPIO_AF_MODE_8 = 8,
    GPIO_AF_MODE_9 = 9,
    GPIO_AF_MODE_10 = 10,
    GPIO_AF_MODE_11 = 11,
    GPIO_AF_MODE_12 = 12,
    GPIO_AF_MODE_13 = 13,
    GPIO_AF_MODE_14 = 14,
    GPIO_AF_MODE_15 = 15,
} gpio_af_mode;

typedef enum {
    GPIO_PUPD_NONE = 0b00,
    GPIO_PULLUP = 0b01,
    GPIO_PULLDOWN = 0b10,
} gpio_pupd;

typedef enum {
    GPIO_SPEED_LOW = 0b00,
    GPIO_SPEED_MED = 0b01,
    GPIO_SPEED_FAST = 0b10,
    GPIO_SPEED_HIGH = 0b11,
} gpio_speed;

typedef enum {
    GPIO_OUTPUT_PUSH_PULL = 0,
    GPIO_OUTPUT_OPEN_DRAIN = 1,
} gpio_output_type;

typedef enum {
    GPIO_CALIB_INPUT_SINGLE_ENDED,
    GPIO_CALIB_INPUT_DIFFERENTIAL,
} gpio_calib_input_mode;

#define HIGH true
#define LOW false

// ===== AF feature enums (only symbols present in your screenshots) =====

// AF0: SYS_AF
typedef enum {
    GPIO_AF0_FEATURE_NONE = 0,
    GPIO_AF0_SYS_JTMS_SWDIO,
    GPIO_AF0_SYS_JTCK_SWCLK,
    GPIO_AF0_SYS_JTDI,
    GPIO_AF0_SYS_JTDO_TRACE_SWO,
    GPIO_AF0_SYS_NJTRST,
    GPIO_AF0_SYS_TRACECK,
    GPIO_AF0_SYS_TRACED0,
    GPIO_AF0_SYS_TRACED1,
    GPIO_AF0_SYS_TRACED2,
    GPIO_AF0_SYS_TRACED3,
    GPIO_AF0_SYS_MCO,
    GPIO_AF0_SYS_RTC_REFIN,
    GPIO_AF0_SYS_RTC_OUT,
    GPIO_AF0_SYS_TRIG_INOUT,
    GPIO_AF0_SYS_LSCO,
} gpio_af0_feature;

// AF1: TIM1 / TIM2 / LPTIM1
typedef enum {
    GPIO_AF1_FEATURE_NONE = 0,
    GPIO_AF1_TIM1_ETR,
    GPIO_AF1_TIM1_BKIN,
    GPIO_AF1_TIM1_BKIN2,
    GPIO_AF1_TIM1_CH1,
    GPIO_AF1_TIM1_CH1N,
    GPIO_AF1_TIM1_CH2,
    GPIO_AF1_TIM1_CH2N,
    GPIO_AF1_TIM1_CH3,
    GPIO_AF1_TIM1_CH3N,
    GPIO_AF1_TIM1_CH4,
    GPIO_AF1_TIM2_CH1,
    GPIO_AF1_TIM2_CH2,
    GPIO_AF1_TIM2_CH3,
    GPIO_AF1_TIM2_CH4,
    GPIO_AF1_LPTIM1_IN1,
    GPIO_AF1_LPTIM1_IN2,
    GPIO_AF1_LPTIM1_OUT,
    GPIO_AF1_LPTIM1_ETR,
} gpio_af1_feature;

// AF2: TIM1 / TIM2 (alt placements)
typedef enum {
    GPIO_AF2_FEATURE_NONE = 0,
    GPIO_AF2_TIM1_BKIN2,
    GPIO_AF2_TIM2_ETR,
} gpio_af2_feature;

// AF3: SPI2 / SAI1 / TIM1
typedef enum {
    GPIO_AF3_FEATURE_NONE = 0,
    GPIO_AF3_SPI2_SCK,
    GPIO_AF3_SPI2_MISO,
    GPIO_AF3_SPI2_MOSI,
    GPIO_AF3_SAI1_PDM_CK1,
    GPIO_AF3_SAI1_PDM_CK2,
    GPIO_AF3_SAI1_PDM_DI1,
    GPIO_AF3_SAI1_PDM_DI2,
    GPIO_AF3_SAI1_PDM_DI3,
    GPIO_AF3_TIM1_BKIN,
} gpio_af3_feature;

// AF4: I2C1 / I2C3
typedef enum {
    GPIO_AF4_FEATURE_NONE = 0,
    GPIO_AF4_I2C1_SMBA,
    GPIO_AF4_I2C1_SCL,
    GPIO_AF4_I2C1_SDA,
    GPIO_AF4_I2C3_SMBA,
    GPIO_AF4_I2C3_SCL,
    GPIO_AF4_I2C3_SDA,
} gpio_af4_feature;

// AF5: SPI1 / SPI2
typedef enum {
    GPIO_AF5_FEATURE_NONE = 0,
    GPIO_AF5_SPI1_NSS,
    GPIO_AF5_SPI1_SCK,
    GPIO_AF5_SPI1_MISO,
    GPIO_AF5_SPI1_MOSI,
    GPIO_AF5_SPI2_NSS,
    GPIO_AF5_SPI2_SCK,
    GPIO_AF5_SPI2_MISO,
    GPIO_AF5_SPI2_MOSI,
} gpio_af5_feature;

// AF6: RF
typedef enum {
    GPIO_AF6_FEATURE_NONE = 0,
    GPIO_AF6_RF_TX_MOD_EXT_PA,
} gpio_af6_feature;

// AF7: USART1
typedef enum {
    GPIO_AF7_FEATURE_NONE = 0,
    GPIO_AF7_USART1_CK,
    GPIO_AF7_USART1_TX,
    GPIO_AF7_USART1_RX,
    GPIO_AF7_USART1_CTS,
    GPIO_AF7_USART1_RTS_DE,
} gpio_af7_feature;

// AF8: LPUART1 / IR
typedef enum {
    GPIO_AF8_FEATURE_NONE = 0,
    GPIO_AF8_LPUART1_TX,
    GPIO_AF8_LPUART1_RX,
    GPIO_AF8_LPUART1_CTS,
    GPIO_AF8_LPUART1_RTS,
    GPIO_AF8_LPUART1_RTS_DE,
    GPIO_AF8_IR_OUT,
} gpio_af8_feature;

// AF9: TSC
typedef enum {
    GPIO_AF9_FEATURE_NONE = 0,
    GPIO_AF9_TSC_G1_IO1,
    GPIO_AF9_TSC_G1_IO2,
    GPIO_AF9_TSC_G1_IO3,
    GPIO_AF9_TSC_G1_IO4,
    GPIO_AF9_TSC_G2_IO1,
    GPIO_AF9_TSC_G2_IO2,
    GPIO_AF9_TSC_G2_IO3,
    GPIO_AF9_TSC_G2_IO4,
    GPIO_AF9_TSC_G3_IO1,
    GPIO_AF9_TSC_G3_IO2,
    GPIO_AF9_TSC_G3_IO3,
    GPIO_AF9_TSC_G3_IO4,
    GPIO_AF9_TSC_G4_IO1,
    GPIO_AF9_TSC_G4_IO2,
    GPIO_AF9_TSC_G4_IO3,
    GPIO_AF9_TSC_G4_IO4,
    GPIO_AF9_TSC_G5_IO1,
    GPIO_AF9_TSC_G5_IO2,
    GPIO_AF9_TSC_G5_IO3,
    GPIO_AF9_TSC_G5_IO4,
    GPIO_AF9_TSC_G6_IO1,
    GPIO_AF9_TSC_G6_IO2,
    GPIO_AF9_TSC_G6_IO3,
    GPIO_AF9_TSC_G6_IO4,
    GPIO_AF9_TSC_G7_IO1,
    GPIO_AF9_TSC_G7_IO2,
    GPIO_AF9_TSC_G7_IO3,
    GPIO_AF9_TSC_G7_IO4,
    GPIO_AF9_TSC_SYNC,
} gpio_af9_feature;

// AF10: USB / QUADSPI
typedef enum {
    GPIO_AF10_FEATURE_NONE = 0,
    GPIO_AF10_USB_DM,
    GPIO_AF10_USB_DP,
    GPIO_AF10_USB_NOE,
    GPIO_AF10_USB_CRS_SYNC,
    GPIO_AF10_QUADSPI_CLK,
    GPIO_AF10_QUADSPI_BK1_NCS,
    GPIO_AF10_QUADSPI_BK1_IO0,
    GPIO_AF10_QUADSPI_BK1_IO1,
    GPIO_AF10_QUADSPI_BK1_IO2,
    GPIO_AF10_QUADSPI_BK1_IO3,
} gpio_af10_feature;

// AF11: LCD
typedef enum {
    GPIO_AF11_FEATURE_NONE = 0,
    GPIO_AF11_LCD_COM0,
    GPIO_AF11_LCD_COM1,
    GPIO_AF11_LCD_COM2,
    GPIO_AF11_LCD_COM3,
    GPIO_AF11_LCD_COM4,
    GPIO_AF11_LCD_COM5,
    GPIO_AF11_LCD_COM6,
    GPIO_AF11_LCD_COM7,
    GPIO_AF11_LCD_SEG0,
    GPIO_AF11_LCD_SEG1,
    GPIO_AF11_LCD_SEG2,
    GPIO_AF11_LCD_SEG3,
    GPIO_AF11_LCD_SEG4,
    GPIO_AF11_LCD_SEG5,
    GPIO_AF11_LCD_SEG6,
    GPIO_AF11_LCD_SEG7,
    GPIO_AF11_LCD_SEG8,
    GPIO_AF11_LCD_SEG9,
    GPIO_AF11_LCD_SEG10,
    GPIO_AF11_LCD_SEG11,
    GPIO_AF11_LCD_SEG12,
    GPIO_AF11_LCD_SEG13,
    GPIO_AF11_LCD_SEG14,
    GPIO_AF11_LCD_SEG15,
    GPIO_AF11_LCD_SEG16,
    GPIO_AF11_LCD_SEG17,
    GPIO_AF11_LCD_SEG18,
    GPIO_AF11_LCD_SEG19,
    GPIO_AF11_LCD_SEG20,
    GPIO_AF11_LCD_SEG21,
    GPIO_AF11_LCD_SEG22,
    GPIO_AF11_LCD_SEG23,
    GPIO_AF11_LCD_SEG24,
    GPIO_AF11_LCD_SEG25,
    GPIO_AF11_LCD_SEG26,
    GPIO_AF11_LCD_SEG27,
    GPIO_AF11_LCD_SEG28,
    GPIO_AF11_LCD_SEG29,
    GPIO_AF11_LCD_SEG30,
    GPIO_AF11_LCD_SEG31,
    GPIO_AF11_LCD_SEG32,
    GPIO_AF11_LCD_SEG33,
    GPIO_AF11_LCD_SEG34,
    GPIO_AF11_LCD_SEG35,
    GPIO_AF11_LCD_SEG36,
    GPIO_AF11_LCD_SEG37,
    GPIO_AF11_LCD_SEG38,
    GPIO_AF11_LCD_SEG39,
    GPIO_AF11_LCD_SEG40,
    GPIO_AF11_LCD_SEG41,
    GPIO_AF11_LCD_SEG42,
    GPIO_AF11_LCD_SEG43,
    GPIO_AF11_LCD_VLCD,
} gpio_af11_feature;

// AF12: COMP1/COMP2/TIM1
typedef enum {
    GPIO_AF12_FEATURE_NONE = 0,
    GPIO_AF12_COMP1_OUT,
    GPIO_AF12_COMP2_OUT,
    GPIO_AF12_TIM1_BKIN2,
} gpio_af12_feature;

// AF13: SAI1
typedef enum {
    GPIO_AF13_FEATURE_NONE = 0,
    GPIO_AF13_SAI1_EXTCLK,
    GPIO_AF13_SAI1_MCLK_A,
    GPIO_AF13_SAI1_MCLK_B,
    GPIO_AF13_SAI1_SCK_A,
    GPIO_AF13_SAI1_SCK_B,
    GPIO_AF13_SAI1_FS_A,
    GPIO_AF13_SAI1_FS_B,
    GPIO_AF13_SAI1_SD_A,
    GPIO_AF13_SAI1_SD_B,
} gpio_af13_feature;

// AF14: TIM2 / TIM16 / TIM17 / LPTIM2
typedef enum {
    GPIO_AF14_FEATURE_NONE = 0,
    GPIO_AF14_TIM2_ETR,
    GPIO_AF14_TIM2_CH1,
    GPIO_AF14_TIM16_CH1,
    GPIO_AF14_TIM16_CH1N,
    GPIO_AF14_TIM16_BKIN,
    GPIO_AF14_TIM17_CH1,
    GPIO_AF14_TIM17_CH1N,
    GPIO_AF14_TIM17_BKIN,
    GPIO_AF14_LPTIM2_IN1,
    GPIO_AF14_LPTIM2_IN2,
    GPIO_AF14_LPTIM2_ETR,
    GPIO_AF14_LPTIM2_OUT,
} gpio_af14_feature;

// AF15: EVENTOUT
typedef enum {
    GPIO_AF15_FEATURE_NONE = 0,
    GPIO_AF15_EVENTOUT,
} gpio_af15_feature;

// ===== Per-pin structure =====

typedef struct {
    gpio_t *gpio;
    uint8_t num;
    adc_channel adc_chan;

    gpio_af0_feature af0_feature : 5;
    gpio_af1_feature af1_feature : 5;
    gpio_af2_feature af2_feature : 3;
    gpio_af3_feature af3_feature : 5;
    gpio_af4_feature af4_feature : 3;
    gpio_af5_feature af5_feature : 4;
    gpio_af6_feature af6_feature : 2;
    gpio_af7_feature af7_feature : 3;
    gpio_af8_feature af8_feature : 3;
    gpio_af9_feature af9_feature : 6;
    gpio_af10_feature af10_feature : 4;
    gpio_af11_feature af11_feature : 6;
    gpio_af12_feature af12_feature : 3;
    gpio_af13_feature af13_feature : 4;
    gpio_af14_feature af14_feature : 5;
    gpio_af15_feature af15_feature : 1;
} gpio_pin_t;

// ===== Pin declarations (only pins from your original header) =====
// (Every cell is copied from the table screenshots you sent.)

// --- PORT A ---
static const gpio_pin_t PA0 = {GPIOA,
                               0,
                               ADC_CHANNEL_5,
                               GPIO_AF0_FEATURE_NONE,
                               GPIO_AF1_TIM2_CH1,
                               GPIO_AF2_FEATURE_NONE,
                               GPIO_AF3_FEATURE_NONE,
                               GPIO_AF4_FEATURE_NONE,
                               GPIO_AF5_FEATURE_NONE,
                               GPIO_AF6_FEATURE_NONE,
                               GPIO_AF7_FEATURE_NONE,
                               GPIO_AF8_FEATURE_NONE,
                               GPIO_AF9_FEATURE_NONE,
                               GPIO_AF10_FEATURE_NONE,
                               GPIO_AF11_FEATURE_NONE,
                               GPIO_AF12_COMP1_OUT,
                               GPIO_AF13_SAI1_EXTCLK,
                               GPIO_AF14_TIM2_ETR,
                               GPIO_AF15_EVENTOUT};

static const gpio_pin_t PA1 = {GPIOA,
                               1,
                               ADC_CHANNEL_6,
                               GPIO_AF0_FEATURE_NONE,
                               GPIO_AF1_TIM2_CH2,
                               GPIO_AF2_FEATURE_NONE,
                               GPIO_AF3_FEATURE_NONE,
                               GPIO_AF4_I2C1_SMBA,
                               GPIO_AF5_SPI1_SCK,
                               GPIO_AF6_FEATURE_NONE,
                               GPIO_AF7_FEATURE_NONE,
                               GPIO_AF8_FEATURE_NONE,
                               GPIO_AF9_FEATURE_NONE,
                               GPIO_AF10_FEATURE_NONE,
                               GPIO_AF11_LCD_SEG0,
                               GPIO_AF12_FEATURE_NONE,
                               GPIO_AF13_FEATURE_NONE,
                               GPIO_AF14_FEATURE_NONE,
                               GPIO_AF15_EVENTOUT};

static const gpio_pin_t PA2 = {GPIOA,
                               2,
                               ADC_CHANNEL_7,
                               GPIO_AF0_SYS_LSCO,
                               GPIO_AF1_TIM2_CH3,
                               GPIO_AF2_FEATURE_NONE,
                               GPIO_AF3_FEATURE_NONE,
                               GPIO_AF4_FEATURE_NONE,
                               GPIO_AF5_FEATURE_NONE,
                               GPIO_AF6_FEATURE_NONE,
                               GPIO_AF7_FEATURE_NONE,
                               GPIO_AF8_LPUART1_TX,
                               GPIO_AF9_FEATURE_NONE,
                               GPIO_AF10_QUADSPI_BK1_NCS,
                               GPIO_AF11_LCD_SEG1,
                               GPIO_AF12_COMP2_OUT,
                               GPIO_AF13_FEATURE_NONE,
                               GPIO_AF14_FEATURE_NONE,
                               GPIO_AF15_EVENTOUT};

static const gpio_pin_t PA3 = {GPIOA,
                               3,
                               ADC_CHANNEL_8,
                               GPIO_AF0_FEATURE_NONE,
                               GPIO_AF1_TIM2_CH4,
                               GPIO_AF2_FEATURE_NONE,
                               GPIO_AF3_SAI1_PDM_CK1,
                               GPIO_AF4_FEATURE_NONE,
                               GPIO_AF5_FEATURE_NONE,
                               GPIO_AF6_FEATURE_NONE,
                               GPIO_AF7_FEATURE_NONE,
                               GPIO_AF8_LPUART1_RX,
                               GPIO_AF9_FEATURE_NONE,
                               GPIO_AF10_QUADSPI_CLK,
                               GPIO_AF11_LCD_SEG2,
                               GPIO_AF12_FEATURE_NONE,
                               GPIO_AF13_SAI1_MCLK_A,
                               GPIO_AF14_FEATURE_NONE,
                               GPIO_AF15_EVENTOUT};

static const gpio_pin_t PA4 = {GPIOA,
                               4,
                               ADC_CHANNEL_9,
                               GPIO_AF0_FEATURE_NONE,
                               GPIO_AF1_FEATURE_NONE,
                               GPIO_AF2_FEATURE_NONE,
                               GPIO_AF3_FEATURE_NONE,
                               GPIO_AF4_FEATURE_NONE,
                               GPIO_AF5_SPI1_NSS,
                               GPIO_AF6_FEATURE_NONE,
                               GPIO_AF7_FEATURE_NONE,
                               GPIO_AF8_FEATURE_NONE,
                               GPIO_AF9_FEATURE_NONE,
                               GPIO_AF10_FEATURE_NONE,
                               GPIO_AF11_LCD_SEG5,
                               GPIO_AF12_FEATURE_NONE,
                               GPIO_AF13_SAI1_FS_B,
                               GPIO_AF14_LPTIM2_OUT,
                               GPIO_AF15_EVENTOUT};

static const gpio_pin_t PA5 = {GPIOA,
                               5,
                               ADC_CHANNEL_10,
                               GPIO_AF0_FEATURE_NONE,
                               GPIO_AF1_TIM2_CH1,
                               GPIO_AF2_TIM2_ETR,
                               GPIO_AF3_FEATURE_NONE,
                               GPIO_AF4_FEATURE_NONE,
                               GPIO_AF5_SPI1_SCK,
                               GPIO_AF6_FEATURE_NONE,
                               GPIO_AF7_FEATURE_NONE,
                               GPIO_AF8_FEATURE_NONE,
                               GPIO_AF9_FEATURE_NONE,
                               GPIO_AF10_FEATURE_NONE,
                               GPIO_AF11_FEATURE_NONE,
                               GPIO_AF12_FEATURE_NONE,
                               GPIO_AF13_SAI1_SD_B,
                               GPIO_AF14_LPTIM2_ETR,
                               GPIO_AF15_EVENTOUT};

static const gpio_pin_t PA6 = {GPIOA,
                               6,
                               ADC_CHANNEL_11,
                               GPIO_AF0_FEATURE_NONE,
                               GPIO_AF1_TIM1_BKIN,
                               GPIO_AF2_FEATURE_NONE,
                               GPIO_AF3_FEATURE_NONE,
                               GPIO_AF4_FEATURE_NONE,
                               GPIO_AF5_SPI1_MISO,
                               GPIO_AF6_FEATURE_NONE,
                               GPIO_AF7_FEATURE_NONE,
                               GPIO_AF8_LPUART1_CTS,
                               GPIO_AF9_FEATURE_NONE,
                               GPIO_AF10_QUADSPI_BK1_IO3,
                               GPIO_AF11_LCD_SEG3,
                               GPIO_AF12_TIM1_BKIN2,
                               GPIO_AF13_FEATURE_NONE,
                               GPIO_AF14_TIM16_CH1,
                               GPIO_AF15_EVENTOUT};

static const gpio_pin_t PA7 = {GPIOA,
                               7,
                               ADC_CHANNEL_12,
                               GPIO_AF0_FEATURE_NONE,
                               GPIO_AF1_TIM1_CH1N,
                               GPIO_AF2_FEATURE_NONE,
                               GPIO_AF3_FEATURE_NONE,
                               GPIO_AF4_I2C3_SCL,
                               GPIO_AF5_SPI1_MOSI,
                               GPIO_AF6_FEATURE_NONE,
                               GPIO_AF7_FEATURE_NONE,
                               GPIO_AF8_FEATURE_NONE,
                               GPIO_AF9_FEATURE_NONE,
                               GPIO_AF10_QUADSPI_BK1_IO2,
                               GPIO_AF11_LCD_SEG4,
                               GPIO_AF12_COMP2_OUT,
                               GPIO_AF13_FEATURE_NONE,
                               GPIO_AF14_TIM17_CH1,
                               GPIO_AF15_EVENTOUT};

static const gpio_pin_t PA8 = {GPIOA,
                               8,
                               ADC_CHANNEL_15,
                               GPIO_AF0_SYS_MCO,
                               GPIO_AF1_TIM1_CH1,
                               GPIO_AF2_FEATURE_NONE,
                               GPIO_AF3_SAI1_PDM_CK2,
                               GPIO_AF4_FEATURE_NONE,
                               GPIO_AF5_FEATURE_NONE,
                               GPIO_AF6_FEATURE_NONE,
                               GPIO_AF7_USART1_CK,
                               GPIO_AF8_FEATURE_NONE,
                               GPIO_AF9_FEATURE_NONE,
                               GPIO_AF10_FEATURE_NONE,
                               GPIO_AF11_LCD_COM0,
                               GPIO_AF12_FEATURE_NONE,
                               GPIO_AF13_SAI1_SCK_A,
                               GPIO_AF14_LPTIM2_OUT,
                               GPIO_AF15_EVENTOUT};

static const gpio_pin_t PA9 = {GPIOA,
                               9,
                               ADC_CHANNEL_16,
                               GPIO_AF0_FEATURE_NONE,
                               GPIO_AF1_TIM1_CH2,
                               GPIO_AF2_FEATURE_NONE,
                               GPIO_AF3_SAI1_PDM_DI2,
                               GPIO_AF4_I2C1_SCL,
                               GPIO_AF5_SPI2_SCK,
                               GPIO_AF6_FEATURE_NONE,
                               GPIO_AF7_USART1_TX,
                               GPIO_AF8_FEATURE_NONE,
                               GPIO_AF9_FEATURE_NONE,
                               GPIO_AF10_FEATURE_NONE,
                               GPIO_AF11_LCD_COM1,
                               GPIO_AF12_FEATURE_NONE,
                               GPIO_AF13_SAI1_FS_A,
                               GPIO_AF14_FEATURE_NONE,
                               GPIO_AF15_EVENTOUT};

static const gpio_pin_t PA10 = {GPIOA,
                                10,
                                ADC_CHANNEL_NONE,
                                GPIO_AF0_FEATURE_NONE,
                                GPIO_AF1_TIM1_CH3,
                                GPIO_AF2_FEATURE_NONE,
                                GPIO_AF3_SAI1_PDM_DI1,
                                GPIO_AF4_I2C1_SDA,
                                GPIO_AF5_FEATURE_NONE,
                                GPIO_AF6_FEATURE_NONE,
                                GPIO_AF7_USART1_RX,
                                GPIO_AF8_FEATURE_NONE,
                                GPIO_AF9_FEATURE_NONE,
                                GPIO_AF10_USB_CRS_SYNC,
                                GPIO_AF11_LCD_COM2,
                                GPIO_AF12_FEATURE_NONE,
                                GPIO_AF13_SAI1_SD_A,
                                GPIO_AF14_TIM17_BKIN,
                                GPIO_AF15_EVENTOUT};

static const gpio_pin_t PA11 = {GPIOA,
                                11,
                                ADC_CHANNEL_NONE,
                                GPIO_AF0_FEATURE_NONE,
                                GPIO_AF1_TIM1_CH4,
                                GPIO_AF2_TIM1_BKIN2,
                                GPIO_AF3_FEATURE_NONE,
                                GPIO_AF4_FEATURE_NONE,
                                GPIO_AF5_SPI1_MISO,
                                GPIO_AF6_FEATURE_NONE,
                                GPIO_AF7_USART1_CTS,
                                GPIO_AF8_FEATURE_NONE,
                                GPIO_AF9_FEATURE_NONE,
                                GPIO_AF10_USB_DM,
                                GPIO_AF11_FEATURE_NONE,
                                GPIO_AF12_TIM1_BKIN2,
                                GPIO_AF13_FEATURE_NONE,
                                GPIO_AF14_FEATURE_NONE,
                                GPIO_AF15_EVENTOUT};

static const gpio_pin_t PA12 = {GPIOA,
                                12,
                                ADC_CHANNEL_NONE,
                                GPIO_AF0_FEATURE_NONE,
                                GPIO_AF1_TIM1_ETR,
                                GPIO_AF2_FEATURE_NONE,
                                GPIO_AF3_FEATURE_NONE,
                                GPIO_AF4_FEATURE_NONE,
                                GPIO_AF5_SPI1_MOSI,
                                GPIO_AF6_FEATURE_NONE,
                                GPIO_AF7_USART1_RTS_DE,
                                GPIO_AF8_LPUART1_RX,
                                GPIO_AF9_FEATURE_NONE,
                                GPIO_AF10_USB_DP,
                                GPIO_AF11_FEATURE_NONE,
                                GPIO_AF12_FEATURE_NONE,
                                GPIO_AF13_FEATURE_NONE,
                                GPIO_AF14_FEATURE_NONE,
                                GPIO_AF15_EVENTOUT};

static const gpio_pin_t PA13 = {GPIOA,
                                13,
                                ADC_CHANNEL_NONE,
                                GPIO_AF0_SYS_JTMS_SWDIO,
                                GPIO_AF1_FEATURE_NONE,
                                GPIO_AF2_FEATURE_NONE,
                                GPIO_AF3_FEATURE_NONE,
                                GPIO_AF4_FEATURE_NONE,
                                GPIO_AF5_FEATURE_NONE,
                                GPIO_AF6_FEATURE_NONE,
                                GPIO_AF7_FEATURE_NONE,
                                GPIO_AF8_IR_OUT,
                                GPIO_AF9_FEATURE_NONE,
                                GPIO_AF10_USB_NOE,
                                GPIO_AF11_FEATURE_NONE,
                                GPIO_AF12_FEATURE_NONE,
                                GPIO_AF13_SAI1_SD_B,
                                GPIO_AF14_FEATURE_NONE,
                                GPIO_AF15_EVENTOUT};

static const gpio_pin_t PA14 = {GPIOA,
                                14,
                                ADC_CHANNEL_NONE,
                                GPIO_AF0_SYS_JTCK_SWCLK,
                                GPIO_AF1_LPTIM1_OUT,
                                GPIO_AF2_FEATURE_NONE,
                                GPIO_AF3_FEATURE_NONE,
                                GPIO_AF4_I2C1_SMBA,
                                GPIO_AF5_FEATURE_NONE,
                                GPIO_AF6_FEATURE_NONE,
                                GPIO_AF7_FEATURE_NONE,
                                GPIO_AF8_FEATURE_NONE,
                                GPIO_AF9_FEATURE_NONE,
                                GPIO_AF10_FEATURE_NONE,
                                GPIO_AF11_LCD_SEG5,
                                GPIO_AF12_FEATURE_NONE,
                                GPIO_AF13_SAI1_FS_B,
                                GPIO_AF14_FEATURE_NONE,
                                GPIO_AF15_EVENTOUT};

static const gpio_pin_t PA15 = {GPIOA,
                                15,
                                ADC_CHANNEL_NONE,
                                GPIO_AF0_SYS_JTDI,
                                GPIO_AF1_TIM2_CH1,
                                GPIO_AF2_TIM2_ETR,
                                GPIO_AF3_FEATURE_NONE,
                                GPIO_AF4_FEATURE_NONE,
                                GPIO_AF5_SPI1_NSS,
                                GPIO_AF6_FEATURE_NONE,
                                GPIO_AF7_FEATURE_NONE,
                                GPIO_AF8_FEATURE_NONE,
                                GPIO_AF9_TSC_G3_IO1,
                                GPIO_AF10_FEATURE_NONE,
                                GPIO_AF11_LCD_SEG17,
                                GPIO_AF12_FEATURE_NONE,
                                GPIO_AF13_FEATURE_NONE,
                                GPIO_AF14_TIM2_CH1,
                                GPIO_AF15_EVENTOUT};

// --- PORT B ---
static const gpio_pin_t PB0 = {GPIOB,
                               0,
                               ADC_CHANNEL_NONE,
                               GPIO_AF0_FEATURE_NONE,
                               GPIO_AF1_FEATURE_NONE,
                               GPIO_AF2_FEATURE_NONE,
                               GPIO_AF3_FEATURE_NONE,
                               GPIO_AF4_FEATURE_NONE,
                               GPIO_AF5_FEATURE_NONE,
                               GPIO_AF6_RF_TX_MOD_EXT_PA,
                               GPIO_AF7_FEATURE_NONE,
                               GPIO_AF8_FEATURE_NONE,
                               GPIO_AF9_FEATURE_NONE,
                               GPIO_AF10_FEATURE_NONE,
                               GPIO_AF11_FEATURE_NONE,
                               GPIO_AF12_COMP1_OUT,
                               GPIO_AF13_FEATURE_NONE,
                               GPIO_AF14_FEATURE_NONE,
                               GPIO_AF15_EVENTOUT};

static const gpio_pin_t PB1 = {GPIOB,
                               1,
                               ADC_CHANNEL_NONE,
                               GPIO_AF0_FEATURE_NONE,
                               GPIO_AF1_FEATURE_NONE,
                               GPIO_AF2_FEATURE_NONE,
                               GPIO_AF3_FEATURE_NONE,
                               GPIO_AF4_FEATURE_NONE,
                               GPIO_AF5_FEATURE_NONE,
                               GPIO_AF6_FEATURE_NONE,
                               GPIO_AF7_FEATURE_NONE,
                               GPIO_AF8_LPUART1_RTS_DE,
                               GPIO_AF9_FEATURE_NONE,
                               GPIO_AF10_FEATURE_NONE,
                               GPIO_AF11_FEATURE_NONE,
                               GPIO_AF12_FEATURE_NONE,
                               GPIO_AF13_FEATURE_NONE,
                               GPIO_AF14_LPTIM2_IN1,
                               GPIO_AF15_EVENTOUT};

static const gpio_pin_t PB2 = {GPIOB,
                               2,
                               ADC_CHANNEL_NONE,
                               GPIO_AF0_SYS_RTC_OUT,
                               GPIO_AF1_LPTIM1_OUT,
                               GPIO_AF2_FEATURE_NONE,
                               GPIO_AF3_FEATURE_NONE,
                               GPIO_AF4_I2C3_SMBA,
                               GPIO_AF5_SPI1_NSS,
                               GPIO_AF6_FEATURE_NONE,
                               GPIO_AF7_FEATURE_NONE,
                               GPIO_AF8_FEATURE_NONE,
                               GPIO_AF9_FEATURE_NONE,
                               GPIO_AF10_FEATURE_NONE,
                               GPIO_AF11_LCD_VLCD,
                               GPIO_AF12_FEATURE_NONE,
                               GPIO_AF13_FEATURE_NONE,
                               GPIO_AF14_FEATURE_NONE,
                               GPIO_AF15_EVENTOUT};

static const gpio_pin_t PB3 = {GPIOB,
                               3,
                               ADC_CHANNEL_NONE,
                               GPIO_AF0_SYS_JTDO_TRACE_SWO,
                               GPIO_AF1_TIM2_CH2,
                               GPIO_AF2_FEATURE_NONE,
                               GPIO_AF3_FEATURE_NONE,
                               GPIO_AF4_FEATURE_NONE,
                               GPIO_AF5_SPI1_SCK,
                               GPIO_AF6_FEATURE_NONE,
                               GPIO_AF7_USART1_RTS_DE,
                               GPIO_AF8_FEATURE_NONE,
                               GPIO_AF9_FEATURE_NONE,
                               GPIO_AF10_FEATURE_NONE,
                               GPIO_AF11_LCD_SEG7,
                               GPIO_AF12_FEATURE_NONE,
                               GPIO_AF13_SAI1_SCK_B,
                               GPIO_AF14_FEATURE_NONE,
                               GPIO_AF15_EVENTOUT};

static const gpio_pin_t PB4 = {GPIOB,
                               4,
                               ADC_CHANNEL_NONE,
                               GPIO_AF0_SYS_NJTRST,
                               GPIO_AF1_FEATURE_NONE,
                               GPIO_AF2_FEATURE_NONE,
                               GPIO_AF3_FEATURE_NONE,
                               GPIO_AF4_I2C3_SDA,
                               GPIO_AF5_SPI1_MISO,
                               GPIO_AF6_FEATURE_NONE,
                               GPIO_AF7_USART1_CTS,
                               GPIO_AF8_FEATURE_NONE,
                               GPIO_AF9_TSC_G2_IO1,
                               GPIO_AF10_FEATURE_NONE,
                               GPIO_AF11_LCD_SEG8,
                               GPIO_AF12_FEATURE_NONE,
                               GPIO_AF13_SAI1_MCLK_B,
                               GPIO_AF14_TIM17_BKIN,
                               GPIO_AF15_EVENTOUT};

static const gpio_pin_t PB5 = {GPIOB,
                               5,
                               ADC_CHANNEL_NONE,
                               GPIO_AF0_FEATURE_NONE,
                               GPIO_AF1_LPTIM1_IN1,
                               GPIO_AF2_FEATURE_NONE,
                               GPIO_AF3_FEATURE_NONE,
                               GPIO_AF4_I2C1_SMBA,
                               GPIO_AF5_SPI1_MOSI,
                               GPIO_AF6_FEATURE_NONE,
                               GPIO_AF7_USART1_CK,
                               GPIO_AF8_LPUART1_TX,
                               GPIO_AF9_TSC_G2_IO2,
                               GPIO_AF10_FEATURE_NONE,
                               GPIO_AF11_LCD_SEG9,
                               GPIO_AF12_COMP2_OUT,
                               GPIO_AF13_SAI1_SD_B,
                               GPIO_AF14_TIM16_BKIN,
                               GPIO_AF15_EVENTOUT};

static const gpio_pin_t PB6 = {GPIOB,
                               6,
                               ADC_CHANNEL_NONE,
                               GPIO_AF0_SYS_MCO,
                               GPIO_AF1_LPTIM1_ETR,
                               GPIO_AF2_FEATURE_NONE,
                               GPIO_AF3_FEATURE_NONE,
                               GPIO_AF4_I2C1_SCL,
                               GPIO_AF5_FEATURE_NONE,
                               GPIO_AF6_FEATURE_NONE,
                               GPIO_AF7_USART1_TX,
                               GPIO_AF8_FEATURE_NONE,
                               GPIO_AF9_TSC_G2_IO3,
                               GPIO_AF10_FEATURE_NONE,
                               GPIO_AF11_LCD_SEG6,
                               GPIO_AF12_FEATURE_NONE,
                               GPIO_AF13_FEATURE_NONE,
                               GPIO_AF14_TIM16_CH1N,
                               GPIO_AF15_EVENTOUT};

static const gpio_pin_t PB7 = {GPIOB,
                               7,
                               ADC_CHANNEL_NONE,
                               GPIO_AF0_FEATURE_NONE,
                               GPIO_AF1_LPTIM1_IN2,
                               GPIO_AF2_TIM1_BKIN,
                               GPIO_AF3_FEATURE_NONE,
                               GPIO_AF4_I2C1_SDA,
                               GPIO_AF5_FEATURE_NONE,
                               GPIO_AF6_FEATURE_NONE,
                               GPIO_AF7_USART1_RX,
                               GPIO_AF8_FEATURE_NONE,
                               GPIO_AF9_TSC_G2_IO4,
                               GPIO_AF10_FEATURE_NONE,
                               GPIO_AF11_LCD_SEG21,
                               GPIO_AF12_FEATURE_NONE,
                               GPIO_AF13_FEATURE_NONE,
                               GPIO_AF14_TIM17_CH1N,
                               GPIO_AF15_EVENTOUT};

static const gpio_pin_t PB8 = {GPIOB,
                               8,
                               ADC_CHANNEL_NONE,
                               GPIO_AF0_FEATURE_NONE,
                               GPIO_AF1_TIM1_CH2N,
                               GPIO_AF2_FEATURE_NONE,
                               GPIO_AF3_SAI1_PDM_CK1,
                               GPIO_AF4_I2C1_SCL,
                               GPIO_AF5_FEATURE_NONE,
                               GPIO_AF6_FEATURE_NONE,
                               GPIO_AF7_FEATURE_NONE,
                               GPIO_AF8_FEATURE_NONE,
                               GPIO_AF9_FEATURE_NONE,
                               GPIO_AF10_FEATURE_NONE,
                               GPIO_AF11_LCD_SEG16,
                               GPIO_AF12_FEATURE_NONE,
                               GPIO_AF13_SAI1_MCLK_A,
                               GPIO_AF14_TIM16_CH1N,
                               GPIO_AF15_EVENTOUT};

static const gpio_pin_t PB9 = {GPIOB,
                               9,
                               ADC_CHANNEL_NONE,
                               GPIO_AF0_FEATURE_NONE,
                               GPIO_AF1_TIM1_CH3N,
                               GPIO_AF2_FEATURE_NONE,
                               GPIO_AF3_SAI1_PDM_DI2,
                               GPIO_AF4_I2C1_SDA,
                               GPIO_AF5_SPI2_NSS,
                               GPIO_AF6_FEATURE_NONE,
                               GPIO_AF7_FEATURE_NONE,
                               GPIO_AF8_IR_OUT,
                               GPIO_AF9_TSC_G7_IO4,
                               GPIO_AF10_QUADSPI_BK1_IO0,
                               GPIO_AF11_LCD_COM3,
                               GPIO_AF12_FEATURE_NONE,
                               GPIO_AF13_SAI1_FS_A,
                               GPIO_AF14_TIM17_CH1,
                               GPIO_AF15_EVENTOUT};

static const gpio_pin_t PB10 = {GPIOB,
                                10,
                                ADC_CHANNEL_NONE,
                                GPIO_AF0_FEATURE_NONE,
                                GPIO_AF1_TIM2_CH3,
                                GPIO_AF2_FEATURE_NONE,
                                GPIO_AF3_FEATURE_NONE,
                                GPIO_AF4_I2C3_SCL,
                                GPIO_AF5_SPI2_SCK,
                                GPIO_AF6_FEATURE_NONE,
                                GPIO_AF7_FEATURE_NONE,
                                GPIO_AF8_LPUART1_RX,
                                GPIO_AF9_TSC_SYNC,
                                GPIO_AF10_QUADSPI_CLK,
                                GPIO_AF11_LCD_SEG10,
                                GPIO_AF12_FEATURE_NONE,
                                GPIO_AF13_SAI1_SCK_A,
                                GPIO_AF14_FEATURE_NONE,
                                GPIO_AF15_EVENTOUT};

static const gpio_pin_t PB11 = {GPIOB,
                                11,
                                ADC_CHANNEL_NONE,
                                GPIO_AF0_FEATURE_NONE,
                                GPIO_AF1_TIM2_CH4,
                                GPIO_AF2_FEATURE_NONE,
                                GPIO_AF3_FEATURE_NONE,
                                GPIO_AF4_I2C3_SDA,
                                GPIO_AF5_FEATURE_NONE,
                                GPIO_AF6_FEATURE_NONE,
                                GPIO_AF7_FEATURE_NONE,
                                GPIO_AF8_LPUART1_TX,
                                GPIO_AF9_FEATURE_NONE,
                                GPIO_AF10_QUADSPI_BK1_NCS,
                                GPIO_AF11_LCD_SEG11,
                                GPIO_AF12_COMP2_OUT,
                                GPIO_AF13_FEATURE_NONE,
                                GPIO_AF14_FEATURE_NONE,
                                GPIO_AF15_EVENTOUT};

static const gpio_pin_t PB12 = {GPIOB,
                                12,
                                ADC_CHANNEL_NONE,
                                GPIO_AF0_FEATURE_NONE,
                                GPIO_AF1_TIM1_BKIN,
                                GPIO_AF2_FEATURE_NONE,
                                GPIO_AF3_SPI2_NSS,
                                GPIO_AF4_I2C3_SMBA,
                                GPIO_AF5_FEATURE_NONE,
                                GPIO_AF6_FEATURE_NONE,
                                GPIO_AF7_FEATURE_NONE,
                                GPIO_AF8_LPUART1_RTS,
                                GPIO_AF9_TSC_G1_IO1,
                                GPIO_AF10_FEATURE_NONE,
                                GPIO_AF11_LCD_SEG12,
                                GPIO_AF12_FEATURE_NONE,
                                GPIO_AF13_SAI1_FS_A,
                                GPIO_AF14_FEATURE_NONE,
                                GPIO_AF15_EVENTOUT};

static const gpio_pin_t PB13 = {GPIOB,
                                13,
                                ADC_CHANNEL_NONE,
                                GPIO_AF0_FEATURE_NONE,
                                GPIO_AF1_TIM1_CH1N,
                                GPIO_AF2_FEATURE_NONE,
                                GPIO_AF3_FEATURE_NONE,
                                GPIO_AF4_I2C3_SCL,
                                GPIO_AF5_SPI2_SCK,
                                GPIO_AF6_FEATURE_NONE,
                                GPIO_AF7_FEATURE_NONE,
                                GPIO_AF8_LPUART1_CTS,
                                GPIO_AF9_TSC_G1_IO2,
                                GPIO_AF10_FEATURE_NONE,
                                GPIO_AF11_LCD_SEG13,
                                GPIO_AF12_FEATURE_NONE,
                                GPIO_AF13_SAI1_SCK_A,
                                GPIO_AF14_FEATURE_NONE,
                                GPIO_AF15_EVENTOUT};

static const gpio_pin_t PB14 = {GPIOB,
                                14,
                                ADC_CHANNEL_NONE,
                                GPIO_AF0_FEATURE_NONE,
                                GPIO_AF1_TIM1_CH2N,
                                GPIO_AF2_FEATURE_NONE,
                                GPIO_AF3_SPI2_MISO,
                                GPIO_AF4_I2C3_SDA,
                                GPIO_AF5_FEATURE_NONE,
                                GPIO_AF6_FEATURE_NONE,
                                GPIO_AF7_FEATURE_NONE,
                                GPIO_AF8_FEATURE_NONE,
                                GPIO_AF9_TSC_G1_IO3,
                                GPIO_AF10_FEATURE_NONE,
                                GPIO_AF11_LCD_SEG14,
                                GPIO_AF12_FEATURE_NONE,
                                GPIO_AF13_SAI1_MCLK_A,
                                GPIO_AF14_FEATURE_NONE,
                                GPIO_AF15_EVENTOUT};

static const gpio_pin_t PB15 = {GPIOB,
                                15,
                                ADC_CHANNEL_NONE,
                                GPIO_AF0_SYS_RTC_REFIN,
                                GPIO_AF1_TIM1_CH3N,
                                GPIO_AF2_FEATURE_NONE,
                                GPIO_AF3_FEATURE_NONE,
                                GPIO_AF4_I2C3_SDA,
                                GPIO_AF5_SPI2_MOSI,
                                GPIO_AF6_FEATURE_NONE,
                                GPIO_AF7_FEATURE_NONE,
                                GPIO_AF8_FEATURE_NONE,
                                GPIO_AF9_TSC_G1_IO4,
                                GPIO_AF10_FEATURE_NONE,
                                GPIO_AF11_LCD_SEG15,
                                GPIO_AF12_FEATURE_NONE,
                                GPIO_AF13_SAI1_SD_A,
                                GPIO_AF14_FEATURE_NONE,
                                GPIO_AF15_EVENTOUT};

// --- PORT C (subset you had) ---
static const gpio_pin_t PC0 = {GPIOC,
                               0,
                               ADC_CHANNEL_1,
                               GPIO_AF0_FEATURE_NONE,
                               GPIO_AF1_LPTIM1_IN1,
                               GPIO_AF2_FEATURE_NONE,
                               GPIO_AF3_FEATURE_NONE,
                               GPIO_AF4_I2C3_SCL,
                               GPIO_AF5_FEATURE_NONE,
                               GPIO_AF6_FEATURE_NONE,
                               GPIO_AF7_FEATURE_NONE,
                               GPIO_AF8_LPUART1_RX,
                               GPIO_AF9_FEATURE_NONE,
                               GPIO_AF10_FEATURE_NONE,
                               GPIO_AF11_LCD_SEG18,
                               GPIO_AF12_FEATURE_NONE,
                               GPIO_AF13_FEATURE_NONE,
                               GPIO_AF14_LPTIM2_IN1,
                               GPIO_AF15_EVENTOUT};

static const gpio_pin_t PC1 = {GPIOC,
                               1,
                               ADC_CHANNEL_2,
                               GPIO_AF0_FEATURE_NONE,
                               GPIO_AF1_LPTIM1_OUT,
                               GPIO_AF2_FEATURE_NONE,
                               GPIO_AF3_SPI2_MOSI,
                               GPIO_AF4_I2C3_SDA,
                               GPIO_AF5_FEATURE_NONE,
                               GPIO_AF6_FEATURE_NONE,
                               GPIO_AF7_FEATURE_NONE,
                               GPIO_AF8_LPUART1_TX,
                               GPIO_AF9_FEATURE_NONE,
                               GPIO_AF10_FEATURE_NONE,
                               GPIO_AF11_LCD_SEG19,
                               GPIO_AF12_FEATURE_NONE,
                               GPIO_AF13_COMP1_INP,
                               GPIO_AF14_FEATURE_NONE,
                               GPIO_AF15_EVENTOUT};

static const gpio_pin_t PC2 = {GPIOC,
                               2,
                               ADC_CHANNEL_3,
                               GPIO_AF0_FEATURE_NONE,
                               GPIO_AF1_LPTIM1_IN2,
                               GPIO_AF2_FEATURE_NONE,
                               GPIO_AF3_FEATURE_NONE,
                               GPIO_AF4_FEATURE_NONE,
                               GPIO_AF5_SPI2_MISO,
                               GPIO_AF6_FEATURE_NONE,
                               GPIO_AF7_FEATURE_NONE,
                               GPIO_AF8_FEATURE_NONE,
                               GPIO_AF9_FEATURE_NONE,
                               GPIO_AF10_FEATURE_NONE,
                               GPIO_AF11_LCD_SEG20,
                               GPIO_AF12_FEATURE_NONE,
                               GPIO_AF13_FEATURE_NONE,
                               GPIO_AF14_FEATURE_NONE,
                               GPIO_AF15_EVENTOUT};

static const gpio_pin_t PC3 = {GPIOC,
                               3,
                               ADC_CHANNEL_4,
                               GPIO_AF0_FEATURE_NONE,
                               GPIO_AF1_LPTIM1_ETR,
                               GPIO_AF2_FEATURE_NONE,
                               GPIO_AF3_SAI1_PDM_DI1,
                               GPIO_AF4_FEATURE_NONE,
                               GPIO_AF5_SPI2_MOSI,
                               GPIO_AF6_FEATURE_NONE,
                               GPIO_AF7_FEATURE_NONE,
                               GPIO_AF8_FEATURE_NONE,
                               GPIO_AF9_FEATURE_NONE,
                               GPIO_AF10_FEATURE_NONE,
                               GPIO_AF11_LCD_VLCD,
                               GPIO_AF12_FEATURE_NONE,
                               GPIO_AF13_SAI1_SD_A,
                               GPIO_AF14_LPTIM2_ETR,
                               GPIO_AF15_EVENTOUT};

static const gpio_pin_t PC4 = {GPIOC,
                               4,
                               ADC_CHANNEL_NONE,
                               GPIO_AF0_FEATURE_NONE,
                               GPIO_AF1_FEATURE_NONE,
                               GPIO_AF2_FEATURE_NONE,
                               GPIO_AF3_FEATURE_NONE,
                               GPIO_AF4_FEATURE_NONE,
                               GPIO_AF5_FEATURE_NONE,
                               GPIO_AF6_FEATURE_NONE,
                               GPIO_AF7_FEATURE_NONE,
                               GPIO_AF8_FEATURE_NONE,
                               GPIO_AF9_FEATURE_NONE,
                               GPIO_AF10_FEATURE_NONE,
                               GPIO_AF11_LCD_SEG22,
                               GPIO_AF12_FEATURE_NONE,
                               GPIO_AF13_FEATURE_NONE,
                               GPIO_AF14_FEATURE_NONE,
                               GPIO_AF15_EVENTOUT};

static const gpio_pin_t PC5 = {GPIOC,
                               5,
                               ADC_CHANNEL_NONE,
                               GPIO_AF0_FEATURE_NONE,
                               GPIO_AF1_FEATURE_NONE,
                               GPIO_AF2_FEATURE_NONE,
                               GPIO_AF3_SAI1_PDM_DI3,
                               GPIO_AF4_FEATURE_NONE,
                               GPIO_AF5_FEATURE_NONE,
                               GPIO_AF6_FEATURE_NONE,
                               GPIO_AF7_FEATURE_NONE,
                               GPIO_AF8_FEATURE_NONE,
                               GPIO_AF9_FEATURE_NONE,
                               GPIO_AF10_FEATURE_NONE,
                               GPIO_AF11_LCD_SEG23,
                               GPIO_AF12_FEATURE_NONE,
                               GPIO_AF13_FEATURE_NONE,
                               GPIO_AF14_FEATURE_NONE,
                               GPIO_AF15_EVENTOUT};

static const gpio_pin_t PC6 = {GPIOC,
                               6,
                               ADC_CHANNEL_NONE,
                               GPIO_AF0_FEATURE_NONE,
                               GPIO_AF1_FEATURE_NONE,
                               GPIO_AF2_FEATURE_NONE,
                               GPIO_AF3_FEATURE_NONE,
                               GPIO_AF4_FEATURE_NONE,
                               GPIO_AF5_FEATURE_NONE,
                               GPIO_AF6_FEATURE_NONE,
                               GPIO_AF7_FEATURE_NONE,
                               GPIO_AF8_FEATURE_NONE,
                               GPIO_AF9_TSC_G4_IO1,
                               GPIO_AF10_FEATURE_NONE,
                               GPIO_AF11_LCD_SEG24,
                               GPIO_AF12_FEATURE_NONE,
                               GPIO_AF13_FEATURE_NONE,
                               GPIO_AF14_FEATURE_NONE,
                               GPIO_AF15_EVENTOUT};

static const gpio_pin_t PC10 = {GPIOC,
                                10,
                                ADC_CHANNEL_NONE,
                                GPIO_AF0_SYS_TRACED1,
                                GPIO_AF1_FEATURE_NONE,
                                GPIO_AF2_FEATURE_NONE,
                                GPIO_AF3_FEATURE_NONE,
                                GPIO_AF4_FEATURE_NONE,
                                GPIO_AF5_FEATURE_NONE,
                                GPIO_AF6_FEATURE_NONE,
                                GPIO_AF7_FEATURE_NONE,
                                GPIO_AF8_FEATURE_NONE,
                                GPIO_AF9_TSC_G3_IO2,
                                GPIO_AF10_FEATURE_NONE,
                                GPIO_AF11_LCD_COM4,
                                GPIO_AF12_FEATURE_NONE,
                                GPIO_AF13_FEATURE_NONE,
                                GPIO_AF14_FEATURE_NONE,
                                GPIO_AF15_EVENTOUT};

static const gpio_pin_t PC11 = {GPIOC,
                                11,
                                ADC_CHANNEL_NONE,
                                GPIO_AF0_FEATURE_NONE,
                                GPIO_AF1_FEATURE_NONE,
                                GPIO_AF2_FEATURE_NONE,
                                GPIO_AF3_FEATURE_NONE,
                                GPIO_AF4_FEATURE_NONE,
                                GPIO_AF5_FEATURE_NONE,
                                GPIO_AF6_FEATURE_NONE,
                                GPIO_AF7_FEATURE_NONE,
                                GPIO_AF8_FEATURE_NONE,
                                GPIO_AF9_TSC_G3_IO3,
                                GPIO_AF10_FEATURE_NONE,
                                GPIO_AF11_LCD_COM5,
                                GPIO_AF12_FEATURE_NONE,
                                GPIO_AF13_FEATURE_NONE,
                                GPIO_AF14_FEATURE_NONE,
                                GPIO_AF15_EVENTOUT};

static const gpio_pin_t PC12 = {GPIOC,
                                12,
                                ADC_CHANNEL_NONE,
                                GPIO_AF0_SYS_TRACED3,
                                GPIO_AF1_FEATURE_NONE,
                                GPIO_AF2_FEATURE_NONE,
                                GPIO_AF3_FEATURE_NONE,
                                GPIO_AF4_FEATURE_NONE,
                                GPIO_AF5_FEATURE_NONE,
                                GPIO_AF6_FEATURE_NONE,
                                GPIO_AF7_FEATURE_NONE,
                                GPIO_AF8_FEATURE_NONE,
                                GPIO_AF9_TSC_G3_IO4,
                                GPIO_AF10_FEATURE_NONE,
                                GPIO_AF11_LCD_COM6,
                                GPIO_AF12_FEATURE_NONE,
                                GPIO_AF13_FEATURE_NONE,
                                GPIO_AF14_FEATURE_NONE,
                                GPIO_AF15_EVENTOUT};

static const gpio_pin_t PC13 = {GPIOC,
                                13,
                                ADC_CHANNEL_NONE,
                                GPIO_AF0_FEATURE_NONE,
                                GPIO_AF1_FEATURE_NONE,
                                GPIO_AF2_FEATURE_NONE,
                                GPIO_AF3_FEATURE_NONE,
                                GPIO_AF4_FEATURE_NONE,
                                GPIO_AF5_FEATURE_NONE,
                                GPIO_AF6_FEATURE_NONE,
                                GPIO_AF7_FEATURE_NONE,
                                GPIO_AF8_FEATURE_NONE,
                                GPIO_AF9_FEATURE_NONE,
                                GPIO_AF10_FEATURE_NONE,
                                GPIO_AF11_FEATURE_NONE,
                                GPIO_AF12_FEATURE_NONE,
                                GPIO_AF13_FEATURE_NONE,
                                GPIO_AF14_FEATURE_NONE,
                                GPIO_AF15_EVENTOUT};

static const gpio_pin_t PC14 = {GPIOC,
                                14,
                                ADC_CHANNEL_NONE,
                                GPIO_AF0_FEATURE_NONE,
                                GPIO_AF1_FEATURE_NONE,
                                GPIO_AF2_FEATURE_NONE,
                                GPIO_AF3_FEATURE_NONE,
                                GPIO_AF4_FEATURE_NONE,
                                GPIO_AF5_FEATURE_NONE,
                                GPIO_AF6_FEATURE_NONE,
                                GPIO_AF7_FEATURE_NONE,
                                GPIO_AF8_FEATURE_NONE,
                                GPIO_AF9_FEATURE_NONE,
                                GPIO_AF10_FEATURE_NONE,
                                GPIO_AF11_FEATURE_NONE,
                                GPIO_AF12_FEATURE_NONE,
                                GPIO_AF13_FEATURE_NONE,
                                GPIO_AF14_FEATURE_NONE,
                                GPIO_AF15_EVENTOUT};

static const gpio_pin_t PC15 = {GPIOC,
                                15,
                                ADC_CHANNEL_NONE,
                                GPIO_AF0_FEATURE_NONE,
                                GPIO_AF1_FEATURE_NONE,
                                GPIO_AF2_FEATURE_NONE,
                                GPIO_AF3_FEATURE_NONE,
                                GPIO_AF4_FEATURE_NONE,
                                GPIO_AF5_FEATURE_NONE,
                                GPIO_AF6_FEATURE_NONE,
                                GPIO_AF7_FEATURE_NONE,
                                GPIO_AF8_FEATURE_NONE,
                                GPIO_AF9_FEATURE_NONE,
                                GPIO_AF10_FEATURE_NONE,
                                GPIO_AF11_FEATURE_NONE,
                                GPIO_AF12_FEATURE_NONE,
                                GPIO_AF13_FEATURE_NONE,
                                GPIO_AF14_FEATURE_NONE,
                                GPIO_AF15_EVENTOUT};

// --- PORT D (only D0–D1 from your file) ---
static const gpio_pin_t PD0 = {GPIOD,
                               0,
                               ADC_CHANNEL_NONE,
                               GPIO_AF0_FEATURE_NONE,
                               GPIO_AF1_FEATURE_NONE,
                               GPIO_AF2_FEATURE_NONE,
                               GPIO_AF3_FEATURE_NONE,
                               GPIO_AF4_FEATURE_NONE,
                               GPIO_AF5_SPI2_NSS,
                               GPIO_AF6_FEATURE_NONE,
                               GPIO_AF7_FEATURE_NONE,
                               GPIO_AF8_FEATURE_NONE,
                               GPIO_AF9_FEATURE_NONE,
                               GPIO_AF10_FEATURE_NONE,
                               GPIO_AF11_FEATURE_NONE,
                               GPIO_AF12_FEATURE_NONE,
                               GPIO_AF13_FEATURE_NONE,
                               GPIO_AF14_FEATURE_NONE,
                               GPIO_AF15_EVENTOUT};

static const gpio_pin_t PD1 = {GPIOD,
                               1,
                               ADC_CHANNEL_NONE,
                               GPIO_AF0_FEATURE_NONE,
                               GPIO_AF1_FEATURE_NONE,
                               GPIO_AF2_FEATURE_NONE,
                               GPIO_AF3_FEATURE_NONE,
                               GPIO_AF4_FEATURE_NONE,
                               GPIO_AF5_SPI2_SCK,
                               GPIO_AF6_FEATURE_NONE,
                               GPIO_AF7_FEATURE_NONE,
                               GPIO_AF8_FEATURE_NONE,
                               GPIO_AF9_FEATURE_NONE,
                               GPIO_AF10_FEATURE_NONE,
                               GPIO_AF11_FEATURE_NONE,
                               GPIO_AF12_FEATURE_NONE,
                               GPIO_AF13_FEATURE_NONE,
                               GPIO_AF14_FEATURE_NONE,
                               GPIO_AF15_EVENTOUT};

// --- PORT E / H (only pins you had) ---
static const gpio_pin_t PE4 = {GPIOE,
                               4,
                               ADC_CHANNEL_NONE,
                               GPIO_AF0_FEATURE_NONE,
                               GPIO_AF1_FEATURE_NONE,
                               GPIO_AF2_FEATURE_NONE,
                               GPIO_AF3_FEATURE_NONE,
                               GPIO_AF4_FEATURE_NONE,
                               GPIO_AF5_FEATURE_NONE,
                               GPIO_AF6_FEATURE_NONE,
                               GPIO_AF7_FEATURE_NONE,
                               GPIO_AF8_FEATURE_NONE,
                               GPIO_AF9_FEATURE_NONE,
                               GPIO_AF10_FEATURE_NONE,
                               GPIO_AF11_FEATURE_NONE,
                               GPIO_AF12_FEATURE_NONE,
                               GPIO_AF13_FEATURE_NONE,
                               GPIO_AF14_FEATURE_NONE,
                               GPIO_AF15_EVENTOUT};

static const gpio_pin_t PH3 = {GPIOH,
                               3,
                               ADC_CHANNEL_NONE,
                               GPIO_AF0_SYS_LSCO,
                               GPIO_AF1_FEATURE_NONE,
                               GPIO_AF2_FEATURE_NONE,
                               GPIO_AF3_FEATURE_NONE,
                               GPIO_AF4_FEATURE_NONE,
                               GPIO_AF5_FEATURE_NONE,
                               GPIO_AF6_FEATURE_NONE,
                               GPIO_AF7_FEATURE_NONE,
                               GPIO_AF8_FEATURE_NONE,
                               GPIO_AF9_FEATURE_NONE,
                               GPIO_AF10_FEATURE_NONE,
                               GPIO_AF11_FEATURE_NONE,
                               GPIO_AF12_FEATURE_NONE,
                               GPIO_AF13_FEATURE_NONE,
                               GPIO_AF14_FEATURE_NONE,
                               GPIO_AF15_EVENTOUT};

// ===== API (unchanged) =====

void gpio_turn_on_port(gpio_t *port);
void gpio_turn_off_port(gpio_t *port);
void gpio_set_mode(gpio_pin_t pin, gpio_mode mode);
void gpio_set_af_mode(gpio_pin_t pin, gpio_af_mode mode);
void gpio_set_pupd(gpio_pin_t pin, gpio_pupd pupd);
void gpio_set_speed(gpio_pin_t pin, gpio_speed speed);
void gpio_set_output_type(gpio_pin_t pin, gpio_output_type type);
void gpio_digital_write(gpio_pin_t pin, bool val);
bool gpio_digital_read(gpio_pin_t pin);
hal_err gpio_enable_interrupt(gpio_pin_t pin);
hal_err gpio_set_interrupt_falling(gpio_pin_t pin);
hal_err gpio_set_interrupt_rising(gpio_pin_t pin);

#endif // HAL_GPIO_H
