#ifndef CONFIG_SETTINGS_H
#define CONFIG_SETTINGS_H

//
//
// Keyboard Settings
//

#ifndef KB_KEY_THRESHOLD_DEFAULT
#define KB_KEY_THRESHOLD_DEFAULT 50
#endif // KB_KEY_THRESHOLD_DEFAULT

#ifndef KB_KEY_MAX_VALUE_THRESHOLD_DEFAULT
#define KB_KEY_MAX_VALUE_THRESHOLD_DEFAULT 1023
#endif // KB_KEY_MAX_VALUE_THRESHOLD_DEFAULT

#ifndef KB_DEFAULT_POLLING_RATE
#define KB_DEFAULT_POLLING_RATE 1
#endif // KB_DEFAULT_POLLING_RATE

#ifndef KB_ADC_SAMPLING_DEFAULT
#define KB_ADC_SAMPLING_DEFAULT ADC_SMP_92_5_CYCLES
#endif // KB_ADC_SAMPLING_DEFAULT

#define KB_KEY_COUNT 24

#define MUX_ENABLED 0

#ifndef DEBUG_UART_ENABLED
#define DEBUG_UART_ENABLED 1
#endif // DEBUG_UART_ENABLED
#ifndef LOG_LEVEL
#define LOG_LEVEL LOG_LEVEL_INFO
#endif // LOG_LEVEL
#define DEBUG_UART_INSTANCE LPUART1
#define DBG_LONG_BLINK_DELAY 1000
#define DBG_SHORT_BLINK_DELAY 300

#endif // SETTINGS_H
