#ifndef CONFIG_MAPPINGS_H
#define CONFIG_MAPPINGS_H

#include "keys.h"
#include "settings.h"
#include "utils/utils.h"

// Mappings:

#define KEY00 KEY_EQUALS_PLUS
#define KEY01 KEY_GRAVEACCENT_TILDE
#define KEY02 KEY_TAB
#define KEY03 KEY_LEFTSHIFT

#define KEY10 KEY_1_EXCLAMATION
#define KEY11 KEY_Q
#define KEY12 KEY_A
#define KEY13 KEY_Z
#define KEY14 KEY_FN

#define KEY20 KEY_2_ATSIGN
#define KEY21 KEY_W
#define KEY22 KEY_S
#define KEY23 KEY_X
#define KEY24 KEY_SLASH_QUESTIONMARK

#define KEY30 KEY_3_NUMBERSIGN
#define KEY31 KEY_E
#define KEY32 KEY_D
#define KEY33 KEY_C
#define KEY34 KEY_LEFTARROW

#define KEY40 KEY_4_DOLLARSIGN
#define KEY41 KEY_R
#define KEY42 KEY_F
#define KEY43 KEY_V
#define KEY44 KEY_RIGHTARROW

#define KEY50 KEY_5_PERCENTSIGN
#define KEY51 KEY_T
#define KEY52 KEY_G
#define KEY53 KEY_B
#define KEY54 KEY_RETURN

#define KEY60 KEY_LEFTCONTROL
#define KEY61 KEY_SPACEBAR

#define KEY70 KEY_LEFTALT
#define KEY71 KEY_FN
#define KEY72 KEY_LAYER

#define KEY80 KEY_RIGHTALT
#define KEY81 KEY_PAGEUP
#define KEY82 KEY_PAGEDOWN

#define KEY90 KEY_RIGHTCONTROL
#define KEY91 KEY_RETURN

#define KEY100 KEY_6_CARET
#define KEY101 KEY_Y
#define KEY102 KEY_H
#define KEY103 KEY_N
#define KEY104 KEY_ESCAPE

#define KEY110 KEY_7_AMPERSAND
#define KEY111 KEY_U
#define KEY112 KEY_J
#define KEY113 KEY_M
#define KEY114 KEY_DOWNARROW

#define KEY120 KEY_8_STAR
#define KEY121 KEY_I
#define KEY122 KEY_K
#define KEY123 KEY_COMMA_LESSTHAN
#define KEY124 KEY_UPARROW

#define KEY130 KEY_9_LPAREN
#define KEY131 KEY_O
#define KEY132 KEY_L
#define KEY133 KEY_DOT_GREATERTHAN
#define KEY134 KEY_SQBRACKETL_CURBRACEL

#define KEY140 KEY_0_RPAREN
#define KEY141 KEY_P
#define KEY142 KEY_SEMICOLON_COLON
#define KEY143 KEY_SLASH_QUESTIONMARK
#define KEY144 KEY_SQBRACKETR_CURBRACER

#define KEY150 KEY_MINUS_UNDERSCORE
#define KEY151 KEY_BACKSLASH_VERTICALBAR
#define KEY152 KEY_APOSTROPHE_QUOTES
#define KEY153 KEY_RIGHTSHIFT

#endif // CONFIG_MAPPINGS_H
