#ifndef TUSB_CONFIG_H
#define TUSB_CONFIG_H

#define BOARD_TUD_RHPORT 0

#define BOARD_TUD_MAX_SPEED OPT_MODE_DEFAULT_SPEED

#define CFG_TUSB_MCU OPT_MCU_STM32WB

#define CFG_TUSB_OS OPT_OS_NONE

#define CFG_TUSB_DEBUG 0

#define CFG_TUD_ENABLED 1

#define CFG_TUD_MAX_SPEED BOARD_TUD_MAX_SPEED

#define CFG_TUSB_MEM_SECTION
#define CFG_TUSB_MEM_ALIGN __attribute__((aligned(4)))

#ifndef CFG_TUD_ENDPOINT0_SIZE
#define CFG_TUD_ENDPOINT0_SIZE 64
#endif

#define CFG_TUD_CDC 0
#define CFG_TUD_MSC 0
#define CFG_TUD_HID 1
#define CFG_TUD_MIDI 0
#define CFG_TUD_VENDOR 0

#define CFG_TUD_HID_EP_BUFSIZE 64

#endif // TUSB_CONFIG_H
