#ifndef MEMORY_MAP_H
#define MEMORY_MAP_H

#include "hal_flash.h"

#define BOOT_CONFIG_ADDRESS FLASH_PAGE_10

#define EEPROM_START_ADDRESS FLASH_PAGE_11

#define APP_START_ADDRESS FLASH_PAGE_20

#define FW_STAGING_ADDRESS FLASH_PAGE_120

#define SECURE_FLASH_ADDRESS FLASH_PAGE_231

#endif // MEMORY_MAP_H
