#ifndef HAL_ERR_H
#define HAL_ERR_H

#include <errno.h>

typedef error_t hal_err;

#define OK 0

#define ERR_NOT_IMPLEMENTED -101

#define ERR_NVIC_SET_PRIO_SP_INV -201
#define ERR_NVIC_SET_PRIO_PP_INV -202

#define ERR_GPIO_SET_INTF_WR_PN -401
#define ERR_GPIO_SET_INTR_WR_PN -402
#define ERR_GPIO_SET_INT_WR_PN -403
#define ERR_GPIO_SET_INT_WR_GPIO -404

#define ERR_SYSTICK_INIT_FREQ_INV -501
#define ERR_SYSTICK_INIT_FREQ_CONFIG -502

#define ERR_CRS_SET_SM_T_INV_TRIM -601

#define ERR_USB_INIT_HANDLE_NULL -701
#define ERR_USB_INIT_INSTANCE_NULL -702

#define ERR_ADC_INIT_BUSY -801
#define ERR_ADC_INIT_INV_SEQ_CONV -802
#define ERR_ADC_INIT_ADVREGEN_FAULT -803
#define ERR_ADC_INIT_CONV_ONGOING -804
#define ERR_ADC_CHCONF_BUSY -805
#define ERR_ADC_CHCONF_INV_OFFSET -806
#define ERR_ADC_CHCONF_INV_OFFSETTYPE -807
#define ERR_ADC_CHCONF_INV_MODE4CH -808
#define ERR_ADC_CHCONF_CONV_ONGOING -809
#define ERR_ADC_DISABLE_CONV_ONGOING -810
#define ERR_ADC_DISABLE_TIMEOUT -811
#define ERR_ADC_ENABLE_REQUIREMENTS -812
#define ERR_ADC_ENABLE_TIMEOUT -813
#define ERR_ADC_CALIB_BUSY -814
#define ERR_ADC_CALIB_TIMEOUT -815
#define ERR_ADC_STARTIT_CONV_ONGOING -816
#define ERR_ADC_STARTIT_BUSY -817
#define ERR_ADC_STOPIT_BUSY -818
#define ERR_ADC_STOPCONV_TIMEOUT -819

#endif // HAL_ERR_H
