#ifndef HAL_ERR_H
#define HAL_ERR_H

#include <errno.h>

typedef error_t hal_err;

#define OK 0

#define ERR_NVIC_SET_PRIO_SP_INV -201
#define ERR_NVIC_SET_PRIO_PP_INV -202

#define ERR_GPIO_ADC_CALIB_DEEPPWD -401
#define ERR_GPIO_ADC_CALIB_ADVREGEN -402
#define ERR_GPIO_ADC_CALIB_ADEN -403
#define ERR_GPIO_ADC_APPLY_CALIB_ADEN -404
#define ERR_GPIO_ADC_APPLY_CALIB_ADSTART -405
#define ERR_GPIO_ADC_APPLY_CALIB_JADSTART -406
#define ERR_GPIO_ADC_SET_ST_NON_ADC -407
#define ERR_GPIO_ADC_SET_ST_NOT_ANALOG -408
#define ERR_GPIO_ADC_SET_RES_ADSTART -409
#define ERR_GPIO_ADC_SET_RES_JADSTART -410
#define ERR_GPIO_ADC_READ_NON_ADC -411
#define ERR_GPIO_ADC_READ_ADEN -412
#define ERR_GPIO_SET_INTF_WR_PN -413
#define ERR_GPIO_SET_INTR_WR_PN -414
#define ERR_GPIO_SET_INT_WR_PN -415
#define ERR_GPIO_SET_INT_WR_GPIO -416

#define ERR_SYSTICK_INIT_FREQ_INV -501
#define ERR_SYSTICK_INIT_FREQ_CONFIG -502

#define ERR_CRS_SET_SM_T_INV_TRIM -601

#define ERR_USB_INIT_HANDLE_NULL -701
#define ERR_USB_INIT_INSTANCE_NULL -702

#endif // HAL_ERR_H
