#ifndef VERSION_H
#define VERSION_H

#include <string.h>

#define YARMANKB_DACTYL_FW_VERSION_BASE "0.1.0"

#ifdef DEBUG
#define YARMANKB_DACTYL_FW_VERSION YARMANKB_DACTYL_FW_VERSION_BASE "-" GIT_HASH
#else
#define YARMANKB_DACTYL_FW_VERSION YARMANKB_DACTYL_FW_VERSION_BASE
#endif // DEBUG

#endif // VERSION_H
